#-------------------------------
# General Site Settings
baseURL = "https://storiwyllt.cymru"
# languageCode = "en-gb"
title = "Stori Wyllt 2026"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
# googleAnalytics = "" # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Pagination settings:

# For Hugo versions 0.128.0 and above, use the following settings:
# This will set the number of items per page for newer versions.
[pagination]
  pagerSize = 6

# For Hugo versions below 0.128.0, uncomment the line below and comment out the [pagination] block above:
#paginate = 6 # Sets the number of items per page for older versions.


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false
