#-------------------------------
# General Site Settings
baseURL = "https://2026.storiwyllt.cymru"
languageCode = "en-gb"
title = "Stori Wyllt 2026"
# googleAnalytics = "" # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Pagination settings:

# For Hugo versions 0.128.0 and above, use the following settings:
# This will set the number of items per page for newer versions.
[pagination]
  pagerSize = 6

# For Hugo versions below 0.128.0, uncomment the line below and comment out the [pagination] block above:
#paginate = 6 # Sets the number of items per page for older versions.

[params]
  logo = "https://res.cloudinary.com/naturceredigion/image/upload/w_200/v1772530714/stori-wyllt-logo.png" # You can add own logo. For example "/images/logo.png".
  logo_dark = "https://res.cloudinary.com/naturceredigion/image/upload/w_200/v1772530714/stori-wyllt-logo.png"
  description = "Stori Wyllt - combining wildlife ID, habitat creation & storytelling"
  color_scheme = "auto" # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the users can choose the light or dark mode themself.

  #-------------------------------
  # Author Settings
  [params.author]
    author_name = "Jake Rayson"

#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 3

  [[menu.main]]
    name = "Schools"
    url = "/schools/"
    weight = 4
    hasChildren = true

      [[menu.main]]
      parent = "Schools"
      name = "Aberteifi"
      url = "/schools/aberteifi/"
      weight = 1

      [[menu.main]]
      parent = "Schools"
      name = "Llanarth"
      url = "/schools/llanarth/"
      weight = 2

      [[menu.main]]
      parent = "Schools"
      name = "Aberaeron"
      url = "/schools/aberaeron/"
      weight = 3

      [[menu.main]]
      parent = "Schools"
      name = "Llanilar"
      url = "/schools/llanilar/"
      weight = 4

  [[menu.main]]
    name = "Workshops"
    url = "/workshops/"
    weight = 4

  [[menu.main]]
    name = "Organise"
    url = "/organise/"
    weight = 5

  # Footer Menu
  [[menu.footer]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.footer]]
  name = "About"
  url = "/about/"
  weight = 2

  [[menu.footer]]
  identifier = "blog"
  name = "Blog"
  url = "/posts/"
  weight = 3

  [[menu.footer]]
  identifier = "artists"
  name = "Artists"
  url = "/artists/"
  weight = 4

  [[menu.footer]]
  identifier = "naturalists"
  name = "Naturalists"
  url = "/naturalists/"
  weight = 5

  [[menu.footer]]
  identifier = "organise"
  name = "Organise"
  url = "/organise/"
  weight = 6


  #-------------------------------
  # Social Settings
  [[params.social]]
    icon = "fa-brands fa-mastodon"
    name = "Mastodon"
    link = "https://en.wikipedia.org/wiki/Mastodon_(social_network)"

  # [[params.social]]
  #   icon = "fa-brands fa-pixelfed"
  #   name = "Pixelfed"
  #   link = "https://pixelfed.social/"

  [[params.social]]
    icon = "fa-brands fa-github"
    name = "GitHub"
    link = "https://github.com/naturceredigion/2026.storiwyllt.cymru"

  # Example of adding a new link to the header and footer:
  # [[params.social]]
  #  icon = "fa-brands fa-youtube"
  #  name = "Youtube"
  #  link = "https://youtube.com"

  # Other icons can be found at https://fontawesome.com/icons


  #-------------------------------
  # Hero Settings
  [params.hero]
    enable = true
    hero_title = "Stori Wyllt <span><i>Wild&nbsp;Story</i></span>" # Add the "span" tag to highlight text.
    hero_description = "Hud bywyd gwyllt i ysgolion drwy adrodd straeon<br><i>Wildlife magic for schools through storytelling</i>"
    hero_image = "https://res.cloudinary.com/naturceredigion/image/upload/v1774544843/250319-llanilar-reccie-river-ystwyth-stone-beach.jpg"
    hero_button_contact = "Blog posts"
    hero_button_about = "Am Stori Wyllt"

  #-------------------------------
  # Schools Settings
  [params.schools]
    enable = true
    schools_title= "Ysgolion <i>Schools</i>"

  #-------------------------------
  # Testimonials Section
  [params.testimonials]
    enable = true
    testimonial_title = "🙂 What people say"

  [[params.testimonial_item]]
    name = "Ysgol Llanarth"
    image = "https://res.cloudinary.com/naturceredigion/image/upload/v1775043960/251015-ysgol-llanarth-mollys-square.jpg"
    designation = "Student"
    link = "https://mylocalschool.gov.wales/School/6672291?lang=en"
    content = "This is better than Xbox!!!"

  #-------------------------------
  # Blog Section
  [params.blog]
    enable = true
    blog_title = "📚 Read latest posts"

  #-------------------------------
  # Tags Section
  [params.tags]
    enable = true
    tags_title = "✌️ Explore topics"

  #-------------------------------
  # Newsletter Settings
  [params.mailchimp]
    enable = true
    mailchimp_title = "For Ceredigion nature news, sign up to Newyddion Natur Ceredigion News"
    mailchimp_identifier = "" # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
    mailchimp_input_text = "Enter your email address"
    mailchimp_background_image = "https://res.cloudinary.com/naturceredigion/image/upload/f_auto/v1720618622/hare-grassland-background.jpg"

  #-------------------------------
  # Footer Settings
  [params.footer]
    footer_description = "I’m Aaron, a creative Illustrator & Art Director based in San Francisco. I seek to push the limits of creativity to create high-engaging and memorable interactive experiences."

  #-------------------------------
  # Contact Settings
  # [params.contact]
  #   contact_email = "your@email.com" # Add your form_id

    # NOTE
    # Simpler theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.

  #-------------------------------
  # Comment Section (Disqus)
  [params.disqus]
    enable = true
    disqusShortname = "anvodstudio-demo" # Add your shortname for Disqus Comment. For example anvodstudio-demo

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false