#-------------------------------
# General Site Settings
baseURL = "https://2026.storiwyllt.cymru"
languageCode = "en-gb"
title = "Stori Wyllt 2026"
# googleAnalytics = "" # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Pagination settings:

# For Hugo versions 0.128.0 and above, use the following settings:
# This will set the number of items per page for newer versions.
[pagination]
  pagerSize = 6

# For Hugo versions below 0.128.0, uncomment the line below and comment out the [pagination] block above:
#paginate = 6 # Sets the number of items per page for older versions.

[params]
  logo = "https://res.cloudinary.com/naturceredigion/image/upload/w_200/v1772530714/stori-wyllt-logo.png" # You can add own logo. For example "/images/logo.png".
  logo_dark = "/images/logo.png"
  description = "Simpler – A modern portfolio theme for Jekyll"
  color_scheme = "auto" # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the users can choose the light or dark mode themself.

  #-------------------------------
  # Author Settings
  [params.author]
    author_name = "Jake Rayson"

#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 3

  [[menu.main]]
    name = "Schools"
    url = "/schools/"
    weight = 4
    hasChildren = true

      [[menu.main]]
      parent = "Schools"
      name = "Aberteifi"
      url = "/schools/aberteifi/"
      weight = 1

      [[menu.main]]
      parent = "Schools"
      name = "Llanarth"
      url = "/schools/llanarth/"
      weight = 2

      [[menu.main]]
      parent = "Schools"
      name = "Aberaeron"
      url = "/schools/aberaeron/"
      weight = 3

      [[menu.main]]
      parent = "Schools"
      name = "Llanilar"
      url = "/schools/llanilar/"
      weight = 4

  [[menu.main]]
    name = "Workshops"
    url = "/workshops/"
    weight = 4
    hasChildren = true

      [[menu.main]]
      parent = "Workshops"
      name = "Workshop 1"
      url = "/workshops/01/"
      weight = 1

      [[menu.main]]
      parent = "Workshops"
      name = "Workshop 2"
      url = "/workshops/02/"
      weight = 2

      [[menu.main]]
      parent = "Workshops"
      name = "Workshop 3"
      url = "/workshops/03/"
      weight = 3

      [[menu.main]]
      parent = "Workshops"
      name = "Workshop 4"
      url = "/workshops/04/"
      weight = 4

      [[menu.main]]
      parent = "Workshops"
      name = "Workshop 5"
      url = "/workshops/05/"
      weight = 4

      # Footer Menu
      [[menu.footer]]
      name = "Home"
      url = "/"
      weight = 1

      [[menu.footer]]
      name = "About"
      url = "/about/"
      weight = 2

      [[menu.footer]]
      identifier = "blog"
      name = "Blog"
      url = "/posts/"
      weight = 4

  #-------------------------------
  # Social Settings
  [[params.social]]
    icon = "fa-brands fa-mastodon"
    name = "Mastodon"
    link = "https://en.wikipedia.org/wiki/Mastodon_(social_network)"

  # [[params.social]]
  #   icon = "fa-brands fa-pixelfed"
  #   name = "Pixelfed"
  #   link = "https://pixelfed.social/"

  [[params.social]]
    icon = "fa-brands fa-github"
    name = "GitHub"
    link = "https://github.com/naturceredigion/2026.storiwyllt.cymru"

  # Example of adding a new link to the header and footer:
  # [[params.social]]
  #  icon = "fa-brands fa-youtube"
  #  name = "Youtube"
  #  link = "https://youtube.com"

  # Other icons can be found at https://fontawesome.com/icons


  #-------------------------------
  # Hero Settings
  [params.hero]
    enable = true
    hero_title = "Stori Wyllt <span><i>Wild&nbsp;Story</i></span>" # Add the "span" tag to highlight text.
    hero_description = "Hud bywyd gwyllt i ysgolion drwy adrodd straeon<br><i>Wildlife magic for schools through storytelling</i>"
    hero_image = "https://via.placeholder.com/1920x1080"
    hero_button_contact = "Get In Touch"
    hero_button_about = "About Me"

  #-------------------------------
  # Schools Settings
  [params.schools]
    enable = true
    schools_title= "Ysgolion <i>Schools</i>"

  #-------------------------------
  # Testimonials Section
  [params.testimonials]
    enable = true
    testimonial_title = "🙂 What Clients Say"

  [[params.testimonial_item]]
    name = "Carla Kenter"
    image = "https://via.placeholder.com/200x200"
    designation = "Professional Artist"
    link = "https://twitter.com/"
    content = "Quisque cursus, metus vitae pharetra auctor, sem massa mattis sem, at interdum magna augue eget diam. Vestibulum ante ipsum primis in faucibus orci luctus"

  [[params.testimonial_item]]
    name = "Kierra Botosh"
    image = "https://via.placeholder.com/200x200"
    designation = "Growth & Community"
    link = "https://facebook.com/"
    content = "Quisque cursus, metus vitae pharetra auctor, sem massa mattis sem, at interdum magna augue eget diam. Vestibulum ante ipsum primis in faucibus orci luctus"

  [[params.testimonial_item]]
    name = "Randy Herwitz"
    image = "https://via.placeholder.com/200x200"
    designation = "Executive Assistant"
    link = "https://twitter.com/"
    content = "Quisque cursus, metus vitae pharetra auctor, sem massa mattis sem, at interdum magna augue eget diam. Vestibulum ante ipsum primis in faucibus orci luctus"

  [[params.testimonial_item]]
    name = "Hanna Franci"
    image = "https://via.placeholder.com/200x200"
    designation = "Product Designer"
    link = "https://facebook.com/"
    content = "Quisque cursus, metus vitae pharetra auctor, sem massa mattis sem, at interdum magna augue eget diam. Vestibulum ante ipsum primis in faucibus orci luctus"

  #-------------------------------
  # Blog Section
  [params.blog]
    enable = true
    blog_title = "📚 Read Latest Posts"

  #-------------------------------
  # Tags Section
  [params.tags]
    enable = true
    tags_title = "✌️ Explore Topics"

  #-------------------------------
  # Newsletter Settings
  [params.mailchimp]
    enable = true
    mailchimp_title = "Get interesting news"
    mailchimp_identifier = "frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3" # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
    mailchimp_input_text = "Enter your email address"
    mailchimp_background_image = "https://via.placeholder.com/1920x1080"

  #-------------------------------
  # Footer Settings
  [params.footer]
    footer_description = "I’m Aaron, a creative Illustrator & Art Director based in San Francisco. I seek to push the limits of creativity to create high-engaging and memorable interactive experiences."

  #-------------------------------
  # Contact Settings
  [params.contact]
    contact_email = "your@email.com" # Add your form_id

    # NOTE
    # Simpler theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.

  #-------------------------------
  # Comment Section (Disqus)
  [params.disqus]
    enable = true
    disqusShortname = "anvodstudio-demo" # Add your shortname for Disqus Comment. For example anvodstudio-demo

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false